# Database connection properties
quarkus.datasource.username=postgres
quarkus.datasource.password=password
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/chronos

# Hibernate ORM configuration
quarkus.hibernate-orm.database.generation=update

quarkus.datasource.jdbc.driver=
