# Database connection properties (samo za dev i prod - testovi koriste Dev Services, tj. svežu bazu u Dockeru)
%dev.quarkus.datasource.username=postgres
%dev.quarkus.datasource.password=password
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/chronos
%prod.quarkus.datasource.username=postgres
%prod.quarkus.datasource.password=password
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/chronos

# Hibernate ORM configuration
quarkus.hibernate-orm.schema-management.strategy=update
%test.quarkus.hibernate-orm.schema-management.strategy=drop-and-create
